- name: Install nginx from APT
  ansible.builtin.apt:
    name:
      - nginx
      - prometheus-nginx-exporter

- name: nginx configuration
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify:
    - restart nginx
    - restart nginx-exporter

- name: Execute handler early
  meta: flush_handlers

- name: nginx service
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - nginx
    - prometheus-nginx-exporter
