{
 "title": "Main",
 "time": { "from": "2024-10-23T16:02:55.243Z", "to": "2024-10-23T16:04:47.111Z" },
 "panels": [
  {
   "title": "InfluxDB status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(influxdb_exporter_stats_query_success)",
     "legendFormat": "__auto"
    },
    { "expr": "(influxdb_write_write_ok)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nginx",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "__auto" },
    { "expr": "(nginx_http_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "My Agama entries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"items\" FROM \"agama-stats\" WHERE \"name\" = '1nnu-1'"
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" },
    {
     "expr": "sum(mysql_global_status_commands_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discovered Agamas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "agama-stats",
     "select": [
      [
       { "params": [ "items" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bind",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "__auto" },
    {
     "expr": "sum(bind_resolver_queries_total{instance=\"1nnu-1:9119\", job=\"bind\", view=\"_default\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "100-(rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))*100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}