---
  - name: Install prometheus
    ansible.builtin.apt:
      name: prometheus

  - name: Put prometheus args
    ansible.builtin.template:
      src: default.prometheus.j2
      dest: /etc/default/prometheus
    notify: Restart Prometheus
    no_log: true

  - name: Configure prometheus
    ansible.builtin.template:
      src: prometheus.yml.j2
      dest: /etc/prometheus/prometheus.yml
    notify: Restart Prometheus
    no_log: true

  - ansible.builtin.service:
      name: prometheus
      state: started
      enabled: true
    
  - name: Add prometheus CNAME records
    community.general.nsupdate:
      key_name: "nsupdate.key"
      key_secret: "{{ dns_nsupdate_key }}"
      key_algorithm: "hmac-sha256"
      zone: "{{ domain }}"
      server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
      record: "prometheus{{ inventory_hostname[-1] if groups['prometheus_servers']|length - 1 else None }}"
      value: "{{ inventory_hostname }}"
      type: "CNAME"
    no_log: true