- name: Install Docker
  ansible.builtin.apt:
    name: docker.io

- name: Check docker enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Install python3-docker
  ansible.builtin.apt:
    name: python3-docker
